import { Router } from 'express';
import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';
dotenv.config();

export const aiRouter = Router();

const genAI = process.env.GEMINI_API_KEY
  ? new GoogleGenerativeAI(process.env.GEMINI_API_KEY)
  : null;

aiRouter.post('/', async (req, res) => {
  try {
    const { mode, type, selectedCode, fullContent, code, language, prompt, instruction } = req.body;

    // Support both legacy 'mode' field and new 'type' field
    const requestType = type || mode;

    if (!requestType) {
      return res.status(400).json({ error: 'Missing required field: type' });
    }

    let fullPrompt = '';

    if (requestType === 'explain') {
      fullPrompt = `You are an expert coding assistant. The user is working in ${language || 'javascript'}.

Here is the full file context:
\`\`\`${language || 'javascript'}
${fullContent || ''}
\`\`\`

The user has selected:
\`\`\`${language || 'javascript'}
${selectedCode || ''}
\`\`\`

Task: Explain what the selected code does step by step. Do NOT write new code, just explain.`;

    } else if (requestType === 'fix') {
      fullPrompt = `You are an expert coding assistant. The user is working in ${language || 'javascript'}.

Here is the full file context:
\`\`\`${language || 'javascript'}
${fullContent || ''}
\`\`\`

The user has selected:
\`\`\`${language || 'javascript'}
${selectedCode || ''}
\`\`\`

Task: Fix the selected code snippet. Return ONLY the fixed code snippet, with no leading text or markdown.`;

    } else if (requestType === 'generate') {
      fullPrompt = `You are an expert coding assistant. The user is working in ${language || 'javascript'}.

Here is the full file context:
\`\`\`${language || 'javascript'}
${fullContent || ''}
\`\`\`

Task: Generate code based on this prompt: "${prompt}". Return ONLY the generated code, properly formatted in a markdown code block.`;

    } else if (requestType === 'inline') {
      // Ctrl+K inline replacement
      fullPrompt = `You are a code editing assistant. Given the selected code and an instruction, produce ONLY the replacement code.

Language: ${language || 'javascript'}
Instruction: "${instruction}"

Selected code:
${code || selectedCode || ''}

Rules:
- Return ONLY the replacement code
- No markdown code fences
- No explanations
- Match the indentation of the original
- Keep the same language`;

    } else if (requestType === 'review') {
      fullPrompt = `Review this ${language || 'javascript'} code. Return ONLY a valid JSON array. Each element:
{ "line": number_or_null, "severity": "error"|"warning"|"info", "message": "string" }

No markdown. No explanation. Just the raw JSON array.

Code:
${code || fullContent || ''}`;

    } else {
      return res.status(400).json({ error: `Unknown request type: ${requestType}` });
    }

    // Mock response when no API key
    if (!genAI) {
      console.warn('[AI] No GEMINI_API_KEY configured — returning mock response.');
      let mockResponse = `[Mock AI Response for: ${requestType}]\n\nSet GEMINI_API_KEY in server/.env to get real responses.`;
      if (requestType === 'generate' || requestType === 'fix') {
        mockResponse += `\n\n\`\`\`${language || 'javascript'}\n// Generated by Mock AI\nfunction setup() {\n  console.log("Mock implementation");\n}\n\`\`\``;
      } else if (requestType === 'inline') {
        mockResponse = '// Mock inline replacement\nconsole.log("AI applied");';
      } else if (requestType === 'review') {
        mockResponse = '[{"line":1,"severity":"info","message":"Mock review — add GEMINI_API_KEY for real analysis"}]';
      }
      // Support both response field names
      return res.json({ response: mockResponse, result: mockResponse });
    }

    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
    const result = await model.generateContent(fullPrompt);
    const text = result.response.text();

    res.json({ response: text, result: text });
  } catch (error) {
    console.error('[AI] Gemini proxy error:', error);
    res.status(500).json({ error: 'AI processing failed. Please try again.' });
  }
});
